    import {
        validatePhoneNumber,
        validateRequired,
        validateMaxLength,
        validateNumber,
        validateMinValue,
        validateMaxValue,
        validateEmail,
        validateRequiredCountry,
        validateRequiredNumber,
        validateRequiredName,
        validateRequiredLastName,
        validateRequiredAddress,
        validateRequiredPostCode,
        validateAcceptedTerms,
        validateRequiredEmail,
        validateRequiredPassword,
        validateRequiredPasswordConfirmation,
        validateRequiredDay,
        validateRequiredTime,
        validateTelephoneNumber,
        validateMinLength,
        validateRequiredMessage,
        validateDomain,
        pipeline,
        pipelineHof
    } from "@nialloc9/vcheck";
    import { FORM_ERROR } from 'final-form'

export {
    validatePhoneNumber,
    validateRequired,
    validateMaxLength,
    validateNumber,
    validateMinValue,
    validateMaxValue,
    validateEmail,
    validateRequiredCountry,
    validateRequiredNumber,
    validateRequiredName,
    validateRequiredLastName,
    validateRequiredAddress,
    validateRequiredPostCode,
    validateAcceptedTerms,
    validateRequiredEmail,
    validateRequiredPassword,
    validateRequiredPasswordConfirmation,
    validateRequiredDay,
    validateRequiredTime,
    validateTelephoneNumber,
    validateMinLength,
    validateRequiredMessage,
    validateDomain,
    pipeline,
    pipelineHof,
    FORM_ERROR
}